# Generated by Django 4.2 on 2023-04-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('creation_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
