# Generated by Django 4.2 on 2023-04-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('amount', models.IntegerField()),
                ('avgBuyPrice', models.FloatField()),
                ('idPortfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.portfolio')),
            ],
        ),
    ]
