# Generated by Django 4.2 on 2023-04-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_cryptocoin_image_url_alter_cryptocoin_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocoin',
            name='image_url',
        ),
    ]
