# Generated by Django 4.2 on 2023-05-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_remove_portfolio_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=3000)),
                ('sender', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
