# Generated by Django 4.2 on 2023-05-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='sender',
        ),
    ]
