# Generated by Django 4.2 on 2023-04-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='login')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
